# Generated by Django 5.1.5 on 2025-02-07 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_offeritem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='valid_unil',
            new_name='valid_until',
        ),
    ]
