# Generated by Django 5.1.5 on 2025-02-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_rename_valid_unil_offer_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
